### ISSUE TITLE
Unit tests about buttons consistently gives errors

### ISSUE THREAD

**Issue by franznoel** [udacity/FEF-Quiz-Angular-Directives#2]
I followed Angular lecture, and I still get unit test errors in the following buttons when using **Udacity Feedback**:
- Clicking the Buy button reduces an item's quantity
- Clicking the Return button increases an item's quantity

**HTML Code:**

```
<div class="panel panel-default panel-sm" ng-class="{'low-stock': info.quantity < 10}" ng-repeat="(size, info) in details">
    <div class="panel-body brick-{{size}}">
        <p class="size">Size: {{size}}</p>
        <p class="quantity">Quantity: {{info.quantity}}</p>
        <p ng-if="info.quantity < 5" class="coming-soon" >Coming Soon</p>
        <p class="price">Price: {{info.price}}</p>
        <button class="btn btn-primary btn-sm buyButton" ng-click="store.buy(color,size)">Buy</button>
        <button class="btn btn-default btn-sm returnButton" ng-click="store.return(color,size)">Return</button>
    </div>
</div>
```

**JavaScript Code** inside the `legoStore` controller:

```
this.buy = function(color,size) {
  this.bricks[color][size].quantity -= 1;
}
this.return = function(color,size) {
  this.bricks[color][size].quantity += 1;
}
```

[Link to Quiz](https://classroom.udacity.com/courses/ud894/lessons/7088388557/concepts/70312685660923)

**Comment by paulmreese** [comment]
Yours was an especially hard case, but the short answer is that it expects the low-stock class to occur on the same element as the brick-1x1 class!

It had to do with the way the grader looked for the buttons, as well as how they were nested.

The grader starts by trying:

```
var brick = document.querySelector('.brick-1x1');
var buyButton = brick.querySelectorAll('button')[0];
var returnButton = brick.querySelectorAll('button')[1];
var itemsShouldBeReturned = false;
```

That means it's really just looking at our first 1x1 block, and then finding the two <button> elements(NOT input[type=button], and it expects them in the order 'buy' then 'return') that are children of the element with a class of "brick-1x1". The last variable sets to true once the script has tested your buy button.

The next part clicks the buy button 4 times, then expects to find the total less than 10, triggering your "low-stock" class, which it looks for on the element with class 'brick-1x1'. This lets the tests know your buy button works with a custom event.

```
buyButton.click();
buyButton.click();
buyButton.click();
buyButton.click();
if (brick.classList.toString().indexOf('low-stock') >= 0) {
    itemsShouldBeReturned = true;
    window.dispatchEvent(new CustomEvent('buy-button-works', 
        {'detail': 'passed'}));
  }
returnButton.click();
returnButton.click();
returnButton.click();
returnButton.click();
if (brick.classList.toString().indexOf('low-stock') === -1 && 
    itemsShouldBeReturned) {
    window.dispatchEvent(new CustomEvent('return-button-works', 
        {'detail': 'passed'}));
}
```

A similar test is done on the return button, setting the total to its original count. This should remove your "low-stock" class and the "itemsShouldBeReturned" variable should be set to true. If both of these conditions are met, then the return button passes as well.

My issue was a combination of the wrong button type and an unexpected DOM tree from the testing perspective.
